### ISSUE TITLE
[Feature Request] Filter hooks

### ISSUE THREAD

**Issue by theldoria** [fourier/ztree#14]
Provide file filter hooks, usable to ignore some files from comparing.

Alternativiely/addition filtering by wildcards/regexp should be possible.

Use-case:
I have to work with a versioning system, which leaves many artifacts. E.g. I frequently find myself with a ton of *.contrib files after merging. Others are *.keep files, left if I undo file hijack. I do not care about those file if I compare directory contents.

**Comment by fourier** [comment]
You can use the ```ztree-diff-filter-list``` variable add your own filters.
