### ISSUE TITLE
Hide compiled files in ztree-dir mode

### ISSUE THREAD

**Issue by madhavan020985** [fourier/ztree#27]
ztree-diff-filter-list, the available feature filters the non-desired file extensions in diff mode.
 
I use ztree-dir to navigate python source directory tree and it shows up .pyc/READ.md  files. And i am not interested in these files. Is there a variable say, ztree-filter-extensions-list that will hide those file extensions in the directory tree.

I tried using ztree-diff-filter-list in ztree-dir mode but that didn't hide the .pyc  files.

**Comment by fourier** [comment]
Thanks for suggestion, I will take a look at it.

**Comment by fourier** [comment]
Done

**Comment by fourier** [comment]
One can use for example
```lisp 
(setq-default ztree-dir-filter-list (cons "^.*\\.pyc" ztree-dir-filter-list))
```
to set the additional filters. Toggle hide/show all files with `H`.
