### ISSUE TITLE
Remove usage of internal TRAMP functions

### ISSUE THREAD

**Issue by fourier** [fourier/ztree#36]
Michael Albinus had proposed the solution on avoiding of usage of the internal TRAMP functions:
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24200
@Silex could you please take a look at this and test if it works for you. If so I'll apply the patch to master and backmerge to the GNU ELPA.

**Comment by Silex** [comment]
Done in #37, I had to also rename the function for it to be consistant with recent changes (remove the `-diff` part).

**Comment by fourier** [comment]
Thanks, merged.
