### ISSUE TITLE
Feature request: ztreedir functions to narrow to a directory and explore parent

### ISSUE THREAD

**Issue by talwrii** [fourier/ztree#42]
I found myself immediately wanting this functionality, so I wrote it:

```
(defun ztreedir-explore-node ()
  (interactive)
  (ztree-dir (ztree-find-node-in-line (line-number-at-pos))))

(defun ztreedir-explore-parent ()
  (interactive)
  (ztree-dir (directory-file-name (file-name-directory ztree-start-node))))
```

I imagine one might also want a go back command as well as keybindings for them (I use evil so these aren't relevant to me)

**Comment by fourier** [comment]
Hi,

I've added proper implementation of this functionality. Now you can narrow to the current directory under cursor (or the parent if it is the file under the cursor) using '>' hotkey. You can use '<' hotkey to explore parent directory. All this happens in the same buffer.

**Comment by talwrii** [comment]
Awesome, thanks.
