### ISSUE TITLE
Feature request: Copy path to clipboard command

### ISSUE THREAD

**Issue by talwrii** [fourier/ztree#44]
Hey there,

Here I'm mostly using your issue list as a discussion forum for things I do with ztree, and to give you a heads-up. If you preferred I didn't do this I could just put this sort of stuff in a private blog post or whatever. Anway...

I found myself wanting to copy paths out of ztree so that I could use them from a terminal:

I wrote myself this function for this:

```
(defun my-ztree-dir-copy-path ()
  (interactive)
  (let ((path (car (ztree-find-node-at-point))))
    (x-set-selection 'PRIMARY path)
    (message "%S" path)))
```

(I'm working around emacs's clipboard settings here...)

**Comment by fourier** [comment]
Hi, 

I would prefer to have real issues/feature requests here. There is a wiki page here, I'll create it later today so this information could be added.

**Comment by fourier** [comment]
Ok, I've created a [wiki](https://github.com/fourier/ztree/wiki) page for this github project, see menu above. Here you can post your tips&tricks.
