### ISSUE TITLE
Dir - lock window size

### ISSUE THREAD

**Issue by nickelas** [fourier/ztree#48]
Feature requests for ztree-dir:
I set the width for ztree-dir so that it matches the content, then when I collapse another window ztree takes that space also and is now way too big. Would be useful to be able to "lock" the size in a simple way.

**Comment by fourier** [comment]
Hi,
The ztree width is dependent on window width. You can press 'g' to refresh ztree window and redraw it.

**Comment by fourier** [comment]
Did it resolve the issue for you ? Can we close it or I didn't understand something from your request?

**Comment by nickelas** [comment]
Ok, thanks.
