### ISSUE TITLE
Show file permission differences

### ISSUE THREAD

**Issue by Ambrevar** [fourier/ztree#50]
I got bitten hard today by an assumption I made, namely that ztree would show file permission differences.

It's an important feature for a file comparison tool, I would love to see this implemented.

**Comment by fourier** [comment]
Thanks for reporting. I'll take a look on how to get file permissions in GNU Emacs; command-line diff tool which I use to compare files doesn't know about file permissions. Out of curiosity, what is the use-case for this feature? I never ever needed anything like this in my professional carrier.

**Comment by Ambrevar** [comment]
Indeed, regular diff tools don't do it.  The only tools I know which do this are `rsync` (e.g. `rsync -nirv --perms --size-only DIR1/ DIR2`) and Beyond Compare (proprietary).

Use case?  Well, file attributes contribute to what defines the files, don't they?  Otherwise they would not be there. `tar` can store them, `rsync` can sync them, `git` preserves them, etc.

More specifically: I was working on product with a huge number of files.  I had 2 versions, 1 was working, the other one was crashing.  I couldn't figure out why since both file trees were identical according to `ztree`.  Until I found out that some executables had had their `x` flag taken away at some point...

**Comment by fourier** [comment]
Hi @Ambrevar , please try the recent version, it will show files with different modes (+x/-x etc) os differences. It doesn't show though what _are_ the differences (yet).

**Comment by fourier** [comment]
Forgot to mention: you have to add `(setq ztree-diff-consider-file-permissions t)` to your config in order for this feature to be active.

**Comment by Ambrevar** [comment]
Nice!  Thanks for that one!  Waiting for more visual details then :D

**Comment by Ambrevar** [comment]
I just tested and it works like a charm!

**Comment by fourier** [comment]
Great. I'll close this issue for now then and open #57 as an enhancement.
