### ISSUE TITLE
Feature request: number of visible files

### ISSUE THREAD

**Issue by rchar01** [fourier/ztree#54]
I think that it would be a good feature to have an option (turn on/off in init file or maybe with shortcut) to show a number of visible files next to directory in ztree-dir, with separate face (e.g. shadow face).
e.g.
```
[-] .emacs.d [3]
 |--[+] auto-save-list [4]
```
and with `show filtered files`:
```
[-] .emacs.d [3]
 |--[+] .trash [11]
 |--[+] auto-save-list [4]
```
What do you think about that?

**Comment by fourier** [comment]
Should this number include directories as well, or just a flat number of entries in a directory? Will it be useful in ztree-diff mode?

**Comment by fourier** [comment]
I've implemented this feature in the corresponding commit. It always show total number of entries(even hidden ones), otherwise it is confusing.

**Comment by rchar01** [comment]
Thanks for the counting feature.
Is there a way to bind this variable to on/off shortcut (e.g `/`)?

**Comment by fourier** [comment]
Bind this function 
```lisp
(defun ztree-toggle-show-number-of-children ()
  (interactive)
  (setf ztree-show-number-of-children (not ztree-show-number-of-children))
  (ztree-refresh-buffer))
```
to some key.
