### ISSUE TITLE
Feature request: cursor position after refreshing

### ISSUE THREAD

**Issue by rchar01** [fourier/ztree#56]
I think it would be a good feature if the cursor did not change its position after refreshing the buffer (ztree-refresh-buffer). Optionally for the user.

Is it possible?
What do you think about it?

**Comment by fourier** [comment]
Yes its not hard to do and could be useful.

**Comment by fourier** [comment]
Please test how does it works for you.

**Comment by rchar01** [comment]
Works great, thanks.

**Comment by fourier** [comment]
Closing it then.

**Comment by fourier** [comment]
Ah it looks like a bug to me. Will take a look at it later.

**Comment by fourier** [comment]
Now it should be fixed. Please close the issue if it works for you and no other related issues has been found.

**Comment by rchar01** [comment]
I don't see anything that needs improvement now, it works great for me.
Thanks for the new feature and fixing the bug.
