### ISSUE TITLE
Feature request: open ztree-dir at point

### ISSUE THREAD

**Issue by rchar01** [fourier/ztree#58]
Similar to the function:
"open Dired with the directory the point is currently on".

I think it would be nice to have the option of opening a new ztree-dir buffer at the current cursor position in ztree-dir (e.g. by hitting "C-t"). Similar to opening a new dired buffer in dired (by hitting `RET`).
The entire open / closed state of the directory subtree will remain unchanged, and it would be easy to return to it by hitting `q`. And just like in dired, if we open the same directory again (ztree-dir at point) the state from the previous visit will be preserved (unless instead of pressing `q` we will use `kill-buffer` to exit).

What do you think about it?

**Comment by fourier** [comment]
Why the widen/narrow is not enough for this?

**Comment by rchar01** [comment]
Using the wide/narrow function the user loses the ability to return to the previously set state of the directory subtree (open/closeed).

It's just an idea, I do not know if users really need this functionality, you can always open a new ztree-dir buffer.

However, I think it is more convenient for the user if ztree-dir would suggests the default directory when used, e.g. when we use ztree-dir from dired buffer, by default, ztree-dir will suggest the directory in which we are located. The default directory for creating a new ztee-dir buffer (from the existing ztree-dir) is "~ /", no difference in what directory we are. Unless we have previously opened the dired buffer, then it is different.

**Comment by fourier** [comment]
You can write a function which will provide the default directory to ztree-dir, and run ztree-dir via this function. Not sure I would need this function in basic functionality, rather on a wiki.

**Comment by fourier** [comment]
You can write something like this for example to open ztree for the directory the current buffer belongs to:
```lisp

(require 'subr-x)
(defun open-ztree-for-current-buffer ()
  "Open ztree in the directory of the current buffer"
  (interactive)
  (when-let ((current-file (buffer-file-name (current-buffer)))
             (dir (file-name-directory current-file)))
    (ztree-dir dir)))
```
and bind it to some hotkey for the mode you are working in or globally. Or write your implementation to whatever suits your needs.

**Comment by rchar01** [comment]
Thanks for the advice, the example you posted doesn't work.

**Comment by fourier** [comment]
Not sure how did you use it.  I just right now put the following to the *scratch* buffer:
```lisp
(require 'subr-x)
(defun open-ztree-for-current-buffer ()
  "Open ztree in the directory of the current buffer"
  (interactive)
  (when-let ((current-file (buffer-file-name (current-buffer)))
             (dir (file-name-directory current-file)))
    (ztree-dir dir)))

(global-set-key [f9] 'open-ztree-for-current-buffer)
```

- then called M-x eval-buffer
- then switched to any other buffer which corresponds to some file
- then press F9 and here we go.

As I said this will do nothing when there is no file associated with the buffer, but you would have to just change when-let to if-let and do the "else" statement providing default directory to the ```ztree-dir``` call

**Comment by rchar01** [comment]
I have used the code in the wrong way, sorry for my complaints.
Thanks for the explanation.

**Comment by fourier** [comment]
Shall I close this issue? Your will do your wrappers for yourself then?

**Comment by fourier** [comment]
Also the wiki on Github shall be available for edit, so you can place your solutions there.

**Comment by rchar01** [comment]
If possible, please leave this thread open.
I will try to write something to work the way I want. I will post the code here in case of problems.

**Comment by fourier** [comment]
Ok I've added my idea to the [wiki](https://github.com/fourier/ztree/wiki#open-ztree-dir-for-current-file), so I'm  closing this issue.
