### ISSUE TITLE
Cursor behavior (dir and diff)

### ISSUE THREAD

**Issue by rchar01** [fourier/ztree#59]
In ztree, when the cursor moves through the directory tree, it has no default position. It can be in any position in the row (column). In dired for example, after pressing `n` or `p` (move down/up) the cursor always returns to the default location (the first letter of the file name).

I do not know if this behavior is desirable in ztree, but I see two advantages:
- Better visibility of the current position in the directory tree, especially when the tree is wide (a lot of subdirectories) it would be more visible at which file the cursor is located. 
I saw the topic "Feature request: add mark functionality". After adding the features described there, it would be good to know what exactly the cursor is pointing at.
- User can copy the name faster, because by default the cursor is already on the first letter of the file name.

e.g. (cursor on the same row)
(cursor on bold X position)
<pre>
Directory tree
==============
[-] .emacs.d
 |--[-] elpa
 |   |--[+] markdown-mode-20180124.138
 |   |--[-] org-20180219
 |   |   |--[-] etc
 |   |   |   |--[-] styles
 |   |   |   |   |----- OrgOdtContentTemplate.xml
 |   |   |   |   |----- OrgOdtStyles.xml
 <b>[X]</b> |   |   |   `----- README
 |   |   |   `----- ORG-NEWS
</pre>
vs. 
(cursor on first letter of REDME file)
<pre>
Directory tree
==============
[-] .emacs.d
 |--[-] elpa
 |   |--[+] markdown-mode-20180124.138
 |   |--[-] org-20180219
 |   |   |--[-] etc
 |   |   |   |--[-] styles
 |   |   |   |   |----- OrgOdtContentTemplate.xml
 |   |   |   |   |----- OrgOdtStyles.xml
 |   |   |   |   `----- <b>[R]</b>EADME
 |   |   |   `----- ORG-NEWS
</pre>

*In the Neotree module (https://github.com/jaypei/emacs-neotree), optional row highlighting is available (for better visibility).*

This is just my opinion based on observations while working in dired and other modules.
I'd like to know what you think about it.

**Comment by fourier** [comment]
You can use hl-line-mode to highlight current line.

**Comment by fourier** [comment]
I don't really want to change the default cursor behavior, it better to be solid agreement between users on it.

**Comment by rchar01** [comment]
Do not get me wrong, I'm not going to force changes in the project.
I just wanted to know your opinion on the subject.

I really like the ztree package (dir and diff) and often think of new functionalities that could make it even better.

**Comment by rchar01** [comment]
Do you think that it would be possible to add a function that allows users to optionally change the default cursor behavior?

*(enable cursor following the file name, as in dired, by editing user init file)*

**Comment by fourier** [comment]
I've started to implement this feature, looks like the part for ztree-dir is done, but ztree-diff is still in progress.

**Comment by fourier** [comment]
Implementation is done, closing the issue. @rchar01 please test and if you encounter something strange report as a new issue.

**Comment by rchar01** [comment]
Thanks.
