### ISSUE TITLE
ztree-dir cursor position

### ISSUE THREAD

**Issue by rchar01** [fourier/ztree#63]
After updating to version 20180408.203 a message appears when moving (`C-n`, `C-f`):
```
ztree-scroll-to-line: Symbol’s function definition is void: offset
```
The cursor behaves as before.
It is not placed at the beginning of the text (according to issue [https://github.com/fourier/ztree/issues/59](https://github.com/fourier/ztree/issues/59)).

_Connected to [https://github.com/fourier/ztree/issues/62](https://github.com/fourier/ztree/issues/62)_

**Comment by fourier** [comment]
Please check after the last commit.

**Comment by rchar01** [comment]
Now it is working great.
The cursor is on the first letter (Just like in dired mode) and there is no error message.
Thanks.

**Comment by fourier** [comment]
Great, closing this issue then.
