### ISSUE TITLE
error when quitting ediff session: ztree-diff-ediff-quit-hook-function: Wrong type argument: window-configuration-p, nil

### ISSUE THREAD

**Issue by hobbes** [fourier/ztree#64]
Hello, 

when I quit an ediff session, I get the following error message, and my ztree-diff window is not restored: 

ztree-diff-ediff-quit-hook-function: Wrong type argument: window-configuration-p, nil

I have to manually C-x 1 and C-x b to the right buffer to continue comparing the directories.

**Comment by fourier** [comment]
Yes this issue shall be resolved with the latest commit, please update as soon as it is available in MELPA.

**Comment by hobbes** [comment]
indeed, updated and issue resolved. Thanks a lot
