### ISSUE TITLE
[Feature request] skip files that differ only in whitespace

### ISSUE THREAD

**Issue by simonpp** [fourier/ztree#65]
It would be useful to have an option (e.g. toggle switch like ediff provides) to skip files that differ only in whitespace / case.

**Comment by fourier** [comment]
Yes it is possible to implement, via command-line options to the diff tool ztree uses as a backend. I'll try to draft implementation real soon.

**Comment by fourier** [comment]
@simonpp now you can set the variable `ztree-diff-additional-options` in your config file with the list of opitons to be provided to the diff, see the README for example.

**Comment by simonpp** [comment]
@fourier, great! Thank you!
