### ISSUE TITLE
Interface with diffoscope?

### ISSUE THREAD

**Issue by Ambrevar** [fourier/ztree#66]
Diffscope seems to provide much of the functionalities of ztree: https://diffoscope.org/.
What about using it as a backend?

**Comment by fourier** [comment]
ztree is a minimalistic directory tree comparison tool using only diff tool as a backend, I dont see a reason to integrate another stand-alone tool with similar functionality into ztree.
It is like to "use midnight commander as a backend for FAR manager". Some parts are common, but why?

**Comment by Ambrevar** [comment]
Just a question out of curiosity.  I think diffoscope could be an interesting study case that could be worthwhile taking inspiration from.
