### ISSUE TITLE
TRAMP support

### ISSUE THREAD

**Issue by Silex** [fourier/ztree#7]
Hello,

First of all, thanks for this nice plugin. It works pretty fine.

My problem is that it _almost_ works over TRAMP except it detects all files as "mismatching". I can browse the results or start ediff sessions just fine, only the detection fails.

Would it be easy to make it work over TRAMP?

**Comment by avoine** [comment]
I think ztree is still detecting all files as mismatching if you compare two directories on two remote servers.

**Comment by fourier** [comment]
@Silex any comments on that ? I never tried to use it over remote at first place.
