### ISSUE TITLE
Wrong directory root in ztree-diff

### ISSUE THREAD

**Issue by michael-heerdegen** [fourier/ztree#80]
Hello,

The difference buffer view of `ztree-diff' has a problem: the roots of the two directory trees both show the name of the "Right" directory, although the diff itself looks correctly (the two dirs are picked up and compared correctly).  Easy to reproduce, happens everytime I use the command.  I'm using the current version provided in the Gnu Elpa repository.

TIA, Michael.

**Comment by fourier** [comment]
Please verify if it works for you. I guess the code will be in ELPA tomorrow, but I'm not sure how often the code gets merged into ELPA from external sources. Otherwise checkout master branch.

**Comment by michael-heerdegen** [comment]
I just checked it out.  Appears to be fixed after quickly testing, thanks.

But are you sure that Gnu Elpa fetches automatically from external sources at all?  In the past it didn't.  Code from external sources was handled differently in the repository (subtrees), but there was no automatic fetch.  Or has that changed?  Melpa does it, yes.

I remember that Stefan Monnier has worked on the Gnu Elpa repository - every package has it's own associated branch now.
